### ISSUE TITLE
建议使用C++语法来实现类的结构

### ISSUE THREAD

**Issue by webary** [fengbingchun/NN_Test#1]
https://github.com/fengbingchun/NN_Test/blob/master/src/NN/CNN.hpp#L121 类中使用了大量的宏定义值magic number，夹杂使用了大量定长数组，以及若干指针变量。
既然类中也有使用vector容器，建议将这些C语言的特性以C++方式实现，就更加灵活易用了

**Comment by fengbingchun** [comment]
@webary 谢谢指出。是需要改成C++方式更灵活，当初只是为了一点一点的实现所以先用的C方式，后来也没调整。
