### ISSUE TITLE
这里pooling层也有w和b么，同时反卷积时卷积核为何没有翻转180

### ISSUE THREAD

**Issue by cnkuangshi** [fengbingchun/NN_Test#2]

**Comment by fengbingchun** [comment]
@cnkuangshi  pooling层也有w和b，实现时参考了tiny-cnn，也并没有对卷积核翻转180

**Comment by cnkuangshi** [comment]
卷积核不翻转不会造成误差传递的错误计算么？一般pooling的做法不都是Average或Max么，这种引入更多参数的Pooling不更容易过拟合么？

**Comment by fengbingchun** [comment]
@cnkuangshi  我还摄入那么深入，后面有时间会进一步研究下
